services:
  - type: web
    name: backend
    env: node
    plan: free
    rootDir: apps/server
    buildCommand: npm install && npm run build
    startCommand: npm run start:dev
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false

  - type: web
    name: frontend
    env: node
    plan: free
    rootDir: apps/mashbak-app
    buildCommand: npm install && npm run build
    startCommand: npm run dev
    envVars:
      - key: REACT_APP_API_URL
        value: https://monorepo-backend.onrender.com

  - type: web
    name: admin
    env: node
    plan: free
    rootDir: apps/admin
    buildCommand: npm install && npm run build
    startCommand: npm run dev
    envVars:
      - key: REACT_APP_API_URL
        value: https://monorepo-backend.onrender.com