services:
  - type: web
    name: monorepo-backend
    env: node
    plan: free
    buildCommand: cd apps/server && npm install && npm run build
    startCommand: cd apps/server && npm run start:dev
    rootDir: server
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false