import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/NavBar/Navbar";
import { Container } from "@mui/material";
import { ReactNode } from "react";
import { Cairo } from "next/font/google";

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-cairo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ar" className={cairo.className} style={{ height: "100%" }}>
      <body>
        <Navbar />
        <Container
          sx={{
            padding: "10px",
            margin: "60px 0",
          }}
        >
          {children}
        </Container>
        {/*<LabelBottomNavigation />*/}
      </body>
    </html>
  );
}
