name: Admin Build

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-client:
    runs-on: [self-hosted, linux, x64, aws]
    working-directory: ./apps/admin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Cache Node.js modules
        uses: actions/cache@v3

      - name: Install dependencies and Vite
        run: |
          npm install
          npm install vite

      - name: Build client
        run: npx vite build
